### ISSUE TITLE
Move does not work if source is not in 'usage'

### ISSUE THREAD

**Issue by acolby** [acolby/creditor#6]
When running creditor 'creditor move selectors my/target other/place' creditor says 'my/target is not an existing directory'.

```
/_src
   /_selectors
      /_my
         /_target
            /_item
               index.js
            /_item2
               index.js
```
               
I'd expect Creditor to still move my/target as there are still items in my/target.

It seems that creditor will only move a directory if the source contains a file for example:

```
/_src
   /_selectors
      /_my
         /_target
            index.js           <------- works if this is here
            /_item
               index.js
            /_item2
               index.js
```
               
We need to make creditor okay with moving an item if it is empty but has sub items.

**Comment by JoshShearer** [comment]
Updated and working correctly.

**Comment by acolby** [comment]
Great! closing issue
