### ISSUE TITLE
Move Functionality

### ISSUE THREAD

**Issue by JoshShearer** [acolby/creditor#9]
It seems action_move will move a file without its associated directory.  the naming conventions in the creditor structure seem as though the directory should travel with the index.js file assuming is has one and is at the end of the directory branch.

When I move this index file....
```
/_src
   /_selectors
      /_my
         /_target
            /_item
               index.js
            /_item2
               index.js   <-----move from
```
I would expect the changes to reflect as shown here...
```
/_src
   /_selectors
      /_my <----Move to Dir
         /_item2
            index.js
         /_target
            /_item
               index.js
           
```
In reality creditor is doing the following...
```
/_src
   /_selectors
      /_my
         index.js  <--- Ends up here
         /_target
            /_item
               index.js
            /_item2 <--- Dir left in path
```

**Comment by acolby** [comment]
This is how Creditor move was intended to work:

if you'd like to move selectors/my/target/item2 to selectors/my/item2 then the move command would expect those two paths as its parameters.

It seems like you are giving the move command selectors/my/target/item2 and selectors/my as parameters. Is this correct?
